// <auto-generated />
namespace wm.Web.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01_UpdateApplicationUserRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_UpdateApplicationUserRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201601100002555_0.1_UpdateApplicationUserRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
