// <auto-generated />
namespace wm.Web.Mirations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Release_001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Release_001));
        
        string IMigrationMetadata.Id
        {
            get { return "201601010949003_Release_00.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
