// <auto-generated />
namespace testRelationships.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01_N : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_N));
        
        string IMigrationMetadata.Id
        {
            get { return "201601021247551_01_N"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
